version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: db-for-go

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_scraper_dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'

    ports:
      - "3306:3306"

    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume:
